### ISSUE TITLE
Hey! Can you help me in changing the color of actionbardrawertoggler

### ISSUE THREAD

**Issue by mohammadn0man** [tuxxon/Drawer-With-Bottom-Navigation#3]
ActionBarDrawerToggle actionBarDrawerToggle = new ActionBarDrawerToggle(this, drawer, toolbar, R.string.open, R.string.close);
drawer.addDrawerListener(actionBarDrawerToggle);
actionBarDrawerToggle.getDrawerArrowDrawable().setColor(getColor(R.color.colorPrimaryDark));
actionBarDrawerToggle.syncState();

in initNavigation() of MainActivity.
I have used this code.
but the problem is when I change fragment the toggler change to white
Please Help,

**Comment by tuxxon** [comment]
Just add a custom theme in styles.xml. If you pull this project again, then you can see the changed toggler.

**Comment by mohammadn0man** [comment]
Thank you so much, bro...
